version: '{build}'
image: Visual Studio 2019
configuration:
- Debug
- Release
init:
- git config --global core.autocrlf true
before_build:
- nuget restore
skip_tags: true
build:
  project: ReferenceAssemblyAnnotator.sln
  verbosity: minimal
test_script:
- git clean -dxf tests
- msbuild /restore tests/MultiTFM /t:Rebuild /p:TreatWarningsAsErrors=true /v:Minimal
artifacts:
- path: 'TunnelVisionLabs.ReferenceAssemblyAnnotator\**\*.nupkg'
