version: '{build}'
image: Visual Studio 2019
configuration:
- Debug
- Release
init:
- git config --global core.autocrlf true
before_build:
- nuget restore
skip_tags: true
build:
  project: ReferenceAssemblyAnnotator.sln
  verbosity: minimal
test_script:
- ps: .\test.ps1 -Clean
artifacts:
- path: 'TunnelVisionLabs.ReferenceAssemblyAnnotator\**\*.nupkg'
